@baseUrl = http://localhost:3000
@userId = 6a43af4f8958d43a98779fbe

### TEST API
GET {{baseUrl}}

### CREATE USER
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe394@example.com",
  "password": "test123"
}

### GET ALL USERS
GET {{baseUrl}}/users

### GET USER BY ID
GET {{baseUrl}}/users/{{userId}}

### UPDATE USER BY ID
PATCH {{baseUrl}}/users/{{userId}}
Content-Type: application/json

{
  "name": "John Doe Updated"
}

### DELETE USER BY ID
DELETE {{baseUrl}}/users/{{userId}}

### CREATE TRIP
POST {{baseUrl}}/trips
Content-Type: application/json
{
  "title": "Trip to the moon",
  "startDate": "2025-3-12",
  "endDate": "2026-1-12",
  "budget": {
    "total": 1000
  },
}